services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/workspace/backend

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/workspace/frontend

  database:
    build:
      context: .
      target: database
    ports:
      - "5432:5432"
    volumes:
      - ./database:/workspace/database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dwengo-database
