services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - /workspace/backend/node_modules
    restart: always

  database:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: database
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/infrastructure/database:/workspace/database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dwengo-database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5