services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - database
    volumes:
      - /workspace/backend/node_modules
    restart: always

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - /workspace/frontend/node_modules
    restart: always

  database:
    build:
      context: .
      target: database
    ports:
      - "5432:5432"
    volumes:
      - ./database:/workspace/database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dwengo-database
