services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    env_file: ".env"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/workspace/backend  # Bind local backend folder to container
      - /workspace/backend/node_modules  # Anonymous volume for node_modules
    restart: always

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "4201:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend:/workspace/frontend  # Bind local frontend folder to container
      - /workspace/frontend/node_modules  # Anonymous volume for node_modules
    restart: always

  database:
    image: postgres:alpine
    ports:
      - "5433:5432"
    volumes:
      - ./backend/src/infrastructure/database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
