services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file: ".env"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - /workspace/backend/node_modules
    restart: always

  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/infrastructure/database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: ".env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
    driver: local