# Backend set-up
FROM node:22-alpine AS backend
WORKDIR /workspace/backend
COPY ./backend/ ./

RUN npm install
RUN npm install -g nodemon ts-node typescript tsconfig-paths pg

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
