name: CI
on:
  pull_request:
jobs:
  backend:
    runs-on: self-hosted
    steps:
      - name: Fix permissions
        run: sudo chown -R $USER:$USER /home/selab2/actions-runner/_work/Dwengo-2/Dwengo-2 || true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Start Postgres
        run: |
          docker run --name pgci \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_DB=dwengo-database \
            -p 5432:5432 \
            -d postgres:15

      - name: Lint backend
        run: npm run lint
        working-directory: backend

      - name: Test backend
        run: npm test
        working-directory: backend

  frontend:
    runs-on: self-hosted
    steps:
      - name: Fix permissions
        run: sudo chown -R $USER:$USER /home/selab2/actions-runner/_work/Dwengo-2/Dwengo-2 || true
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Lint frontend
        run: npm run lint
        working-directory: frontend

      - name: Test frontend
        run: npm test
        working-directory: frontend
        env:
          CHROME_BIN: "/usr/bin/chromium-browser"
