name: CI
on:
  pull_request:
jobs:
  backend:
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Fix permissions
        run: sudo chown -R $USER:$USER /home/selab2/actions-runner/_work/Dwengo-2/Dwengo-2 || true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Lint backend
        run: npm run lint
        working-directory: backend

      - name: Load env vars and test backend
        run: |
          set -a
          source /home/selab2/Dwengo-2/.env
          set +a
          npm test
        working-directory: backend
        env:
          CI: "true"

  frontend:
    runs-on: self-hosted
    steps:
      - name: Fix permissions
        run: sudo chown -R $USER:$USER /home/selab2/actions-runner/_work/Dwengo-2/Dwengo-2 || true
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Lint frontend
        run: npm run lint
        working-directory: frontend

      - name: Unit tests frontend
        run: npm test
        working-directory: frontend
        env:
          CHROME_BIN: "/usr/bin/google-chrome-stable"
      - name: Build Docker image 
        run: docker compose build
      
      - name: Copy .env file to working directory
        run: cp /home/selab2/Dwengo-2/.env-no-port /home/selab2/actions-runner/_work/Dwengo-2/Dwengo-2/.env
      
      - name: Stop old containers
        run: docker compose down
      
      - name: Start new container
        run: docker compose up -d
      
      - name: Wait for frontend to respond
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:4201 > /dev/null; then
              echo "Frontend is up!";
              break;
            fi
            echo "Waiting for frontend...";
            sleep 2;
          done
      
      - name: Serving integration tests frontend
        run: docker exec dwengo-2-frontend-1 ng serve --configuration=e2e --port=4202 &
        working-directory: frontend

      - name: Wait for frontend to respond
        run: |
          for i in {1..30}; do
            if docker exec dwengo-2-frontend-1 curl -s http://localhost:4202 > /dev/null; then
              echo "Frontend is up!";
              break;
            fi
            echo "Waiting for frontend...";
            sleep 2;
          done

      - name: Integration tests frontend (CHROME)
        run: docker exec dwengo-2-frontend-1 npm run e2e:chrome
        working-directory: frontend
        env:
          CHROME_BIN: "/usr/bin/chromium"
          CHROMEDRIVER_BIN: "/usr/bin/chromedriver"
          FIREFOX_BIN: "/usr/bin/firefox"

      - name: Clear end-to-end test database
        run: docker exec dwengo-2-backend-1 npm run db:clear

      # - name: Integration tests frontend (FIREFOX)
      #   run: docker exec dwengo-2-frontend-1 npm run e2e:firefox
      #   working-directory: frontend
      #   env:
      #     CHROME_BIN: "/usr/bin/chromium"
      #     CHROMEDRIVER_BIN: "/usr/bin/chromedriver"
      #     FIREFOX_BIN: "/usr/bin/firefox"
      
      # Always stop testing containers
      - name: Stop containers
        if: always()
        run: docker compose down
