name: CI
on:
  push:
    branches:
      - 318-impromevement-to-ci
  pull_request:

jobs:
  # Only runs if there are changes to the backend
  backend:
    runs-on: self-hosted
    if: contains(github.event.pull_request.head.ref, 'backend/')
    steps:
      - name: Lint backend
        run: cd backend && npm run lint

      - name: Test backend
        run: cd backend && npm run test

  # Only runs if there are changes to the frontend
  frontend:
    runs-on: self-hosted
    if: contains(github.event.pull_request.head.ref, 'frontend/')
    steps:
      - name: Lint frontend
        run: npm run lint

      - name: Test frontend
        run: npm test
