name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: self-hosted
    steps:
      - name: Fix permissions
        run: sudo chown -R $USER:$USER /home/selab2/actions-runner/_work/Dwengo-2/Dwengo-2 || true

      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker compose -f compose.yaml build

      - name: Stop old containers
        run: docker compose -f compose.yaml down

      - name: Start new containers
        run: docker compose -f compose.yaml up -d

      - name: Lint backend
        run: docker exec $(docker ps -qf "name=dwengo-2-backend") npm run lint

      - name: Lint frontend
        run: docker exec $(docker ps -qf "name=dwengo-2-frontend") npm run lint

      - name: Test backend
        run: docker exec $(docker ps -qf "name=dwengo-2-backend") npm test

      - name: Test frontend
        run: docker exec $(docker ps -qf "name=dwengo-2-frontend") npm test
      
      - name: Stop containers # Make sure containers will be stopped even if testing/linting fails
        if: always()
        run: docker compose down