name: CI
on:
  pull_request:
jobs:
  backend:
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Fix permissions
        run: sudo chown -R $USER:$USER /home/selab2/actions-runner/_work/Dwengo-2/Dwengo-2 || true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Lint backend
        run: npm run lint
        working-directory: backend

      - name: Load env vars and test backend
        run: |
          set -a
          source /home/selab2/Dwengo-2/.env
          set +a
          npm test
        working-directory: backend
        env:
          CI: "true"

  frontend:
    runs-on: self-hosted
    steps:
      - name: Fix permissions
        run: sudo chown -R $USER:$USER /home/selab2/actions-runner/_work/Dwengo-2/Dwengo-2 || true
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Lint frontend
        run: npm run lint
        working-directory: frontend

      - name: Unit tests frontend
        run: npm test
        working-directory: frontend
        env:
          CHROME_BIN: "/usr/bin/google-chrome-stable"
      
      # - name: Integration tests frontend
      #   run: npm run e2e-ci:test
      #   working-directory: frontend
      #   env:
      #     CHROME_BIN: "/snap/bin/chromium"
      #     CHROMEDRIVER_BIN: "/usr/bin/chromedriver"
      #     FIREFOX_BIN: "/usr/bin/firefox"
