name: CI
on:
  pull_request:

jobs:
  docker-setup:
    runs-on: self-hosted
    steps:
      - name: Fix permissions
        run: sudo chown -R $USER:$USER /home/selab2/actions-runner/_work/Dwengo-2/Dwengo-2 || true

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose -f compose.yaml build

      - name: Stop old containers
        run: docker compose -f compose.yaml down

      - name: Start new containers
        run: docker compose -f compose.yaml up -d

  backend:
    runs-on: self-hosted
    needs: docker-setup
    if: contains(github.event.pull_request.head.ref, 'backend/')
    steps:
      - name: Lint backend
        run: docker exec $(docker ps -qf "name=dwengo-2-backend") npm run lint

      - name: Test backend
        run: docker exec $(docker ps -qf "name=dwengo-2-backend") npm test

  frontend:
    runs-on: self-hosted
    needs: docker-setup
    if: contains(github.event.pull_request.head.ref, 'frontend/')
    steps:
      - name: Lint frontend
        run: docker exec $(docker ps -qf "name=dwengo-2-frontend") npm run lint

      - name: Test frontend
        run: docker exec $(docker ps -qf "name=dwengo-2-frontend") npm test

  stop-containers:
    runs-on: self-hosted
    needs: [backend, frontend, docker-setup]
    if: always()
    steps:
      - name: Stop containers
        run: docker compose down
